[package]
name = "test-suite"
version = "0.0.0"
authors = ["Yu Onaga <ursus.cauda.elongata@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde_json = "1"

[dependencies.pipitor]
version = "=0.3.0-alpha.9"
default-features = false
