name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          default: true
      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache Cargo target
        uses: actions/cache@v1
        with:
          path: test-suite/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --verbose --manifest-path test-suite/Cargo.toml
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path test-suite/Cargo.toml
