name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install `dhall-to-json`
        run: |
          curl -L 'https://github.com/dhall-lang/dhall-haskell/releases/download/1.36.0/dhall-json-1.7.3-x86_64-linux.tar.bz2' |
          sudo tar -xjC /usr/local ./bin/dhall-to-json
      - name: Setup `credentials.dhall` placeholder
        run: mv credentials{.placeholder,}.dhall
      - run: dhall-to-json --compact --file Pipitor.dhall --output Pipitor.json
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --verbose --manifest-path test-suite/Cargo.toml
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path test-suite/Cargo.toml
