name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1.0.3
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Install `dhall-to-json`
        run: |
          curl -L 'https://github.com/dhall-lang/dhall-haskell/releases/download/1.36.0/dhall-json-1.7.3-x86_64-linux.tar.bz2' |
          sudo tar -xjC /usr/local ./bin/dhall-to-json
      - run: dhall-to-json --compact --file Pipitor.dhall --output Pipitor.json
      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache Cargo target
        uses: actions/cache@v1
        with:
          path: test-suite/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --verbose --manifest-path test-suite/Cargo.toml
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path test-suite/Cargo.toml
